- name: Upload
  logo: /img/Upload_logo.png
  featured: true
  url: upload
- name: Annotator
  logo: /img/Annotator_logo.png
  featured: true
  url: annotator
- name: Knowledge-translation
  logo: /img/Knowledge_translation_logo.png
  featured: true
  url: Knowledge_translation
- name: Knowledge Embedder
  logo: /img/K_embedder_logo.png
  featured: true
  url: knowledge_embedder
- name: FCA generator 
  logo: /img/FCA_logo.png
  featured: true
  url: FCA_generator
- name: Visualization generator
  logo: /img/Visualization_gen_logo.png
  featured: true
  url: Visualization_generator
- name: Cue generator 
  logo: /img/Cue_gen_logo.png
  featured: true
  url: Cue_generator