# To add fields, make a new schema file in this directory
# and change the schema setting in _config.yml to its name
dataset_fields:
  - field_name: title
    label: Title
    datajson: title
  - field_name: notes
    label: DatDescription
    form_template: form/textarea.html
    datajson: description
  - field_name: distribution
    label: Distribution
    datajson: distribution
  - field_name: organization
    label: Organization
    form_template: form/organization.html
    datajson: publisher.name
  - field_name: keyword
    label: DatKeyword
    datajson: keyword
  - field_name: publisher
    label: DatPublisher
    datajson: publisher
  - field_name: category
    label: DatDomain
    form_template: form/category.html
    display_template: display/category.html
    datajson: category
  - field_name: versionNotes 
    label: VersionNotes
    datajson: versionNotes
  - field_name: landingPage 
    label: LandingPage
    datajson: landingPage
  - field_name: accessRigths
    label: AccessRigths
    datajson: accessRigths
  - field_name: creator 
    label: DatCreator
    datajson: creator
  - field_name: hasVersion 
    label: HasVersion
    datajson: hasVersion
  - field_name: isVersionOf 
    label: isVersionOf
    datajson: isVersionOf
  - field_name: DatPublicationTimeStamp
    label: DatPublicationTimeStamp
    datajson: datPublicationTimeStamp
  - field_name: modified
    label: Modified
    datajson: modified
  - field_name: language 
    label: DatLanguage
    datajson: language
  - field_name: provenance 
    label: Provenance
    datajson: provenance
  - field_name: page
    label: Page
    datajson: page
  - field_name: wasGeneratedBy 
    label: WasGeneratedBy
    datajson: wasGeneratedBy
  - field_name: versionInfo 
    label: DatVersion
    datajson: versionInfo 
  - field_name: formalityLevel
    label: LKDatType
    datajson: formalityLevel
  - field_name: DatOwner
    label: DatOwner
    datajson: datOwner
  - field_name: acronym
    label: Acronym
    datajson: acronym
  - field_name: CompetencyQuestion
    label: Competency Question
    datajson: CompetencyQuestion
  - field_name: preferredNamespacePrefix
    label: Preferred Namespace Prefix
    datajson: preferredNamespacePrefix
  - field_name: toDoList
    label: To Do List
    datajson: toDoList
  - field_name: namespacesGenerated
    label: Namespaces Generated
    datajson: namespacesGenerated  
  - field_name: namespacesReused
    label: Namespaces Reused
    datajson: namespacesReused 
  - field_name: datasetLevel
    label: DatLevel
    datajson: datasetLevel
  - field_name: spatialExtent
    label: Spatial Extent
    datajson: spatialExtent
  - field_name: temporalExtent
    label: Temporal Extent
    datajson: temporalExtent
  - field_name: ontologyLanguage
    label: DatFormat
    datajson: ontologyLanguage
  - field_name: license
    label: DatLicense
    datajson: distribution.license
  - field_name: byteSize
    label: DatSize
    datajson: distribution.bytesize
  
resource_fields:
  - field_name: name
    label: Resource Name
    datajson: distribution.title
  - field_name: url
    label: URL
    datajson: distribution.downloadURL
  - field_name: format
    label: Format
    datajson: distribution.format
    form_template: form/dropdown.html
    values:
      - api
      - csv
      - rdf
      - json
      - geojson
      - html
      - kml
      - kmz
      - shp
      - xml
      - owl
  - field_name: description
    label: Description
    datajson: distribution.description 
  - field_name: status
    label: Status
    datajson: distribution.status
    form_template: form/dropdown.html
    values:
    - Unannotated
    - Partially annotated
    - Annotated
  - field_name: issued
    label: Issued
    datajson: distribution.issued
    type: DateTime<'Y-m-d'>
  - field_name: language
    label: Language
    datajson: distribution.language
  - field_name: modified 
    label: Modified
    datajson:  distribution.modified
  - field_name: OntologyEngineeringTool
    label: Ontology Engineering Tool
    datajson: OntologyEngineeringTool
  - field_name: ontologySyntax
    label: Ontology Syntax
    datajson: ontologySyntax
  - field_name: example 
    label: Example Of Use
    datajson: example
  - field_name: ReferenceLKRepository
    label: Reference LK Repository section
    datajson: ReferenceLKRepository
    form_template: form/dropdown.html
    values:
    - SREP
    - CREP
    - DREP
  - field_name: referenceOntology
    label: Reference Ontology 
    datajson: referenceOntology
  - field_name: referenceDatasets
    label: Example Datasets
    datajson: referenceDatasets

organization_fields:
  - field_name: title
    label: Title
  - field_name: description
    label: Description
  - field_name: logo
    label: Logo

category_fields:
  - field_name: name
    label: Name
  - field_name: logo
    label: Logo
  - field_name: logo_credit
    label: Logo Credit
  - field_name: featured
    label: Featured on Homepage
    form_template: form/checkbox.html
      

#DEFAULT SCHEMA:
#dataset_fields:
#  - field_name: title
#    label: Title
#    datajson: title
#  - field_name: organization
#    label: Organization
#    form_template: form/organization.html
#    datajson: publisher.name
#  - field_name: notes
#    label: Description
#    form_template: form/textarea.html
#    datajson: description
#  - field_name: license
#    label: License
#    form_template: form/license.html
#    datajson: license
#  - field_name: category
#    label: Category
#    form_template: form/category.html
#    display_template: display/category.html
#    datajson: category
#  - field_name: maintainer
#    label: Maintainer
#    datajson: contactPoint.fn
#  - field_name: maintainer_email
#    label: Maintainer Email
#    datajson: contactPoint.hasEmail
#  - field_name: tags
#    label: Tags
#    datajson: tags

#resource_fields:
#  - field_name: name
#    label: Resource Name
#    datajson: distribution.title
#  - field_name: url
#    label: URL
#    datajson: distribution.downloadURL
#  - field_name: format
#    label: Format
#    datajson: distribution.format
#    form_template: form/dropdown.html
#    values:
#      - api
#      - csv
#      - rdf
#      - json
#      - geojson
#      - html
#      - kml
#      - kmz
#      - shp
#      - xml

#organization_fields:
#  - field_name: title
#    label: Title
#  - field_name: description
#    label: Description
#  - field_name: logo
#    label: Logo

#category_fields:
#  - field_name: name
#    label: Name
#  - field_name: logo
#    label: Logo
#  - field_name: logo_credit
#    label: Logo Credit
#  - field_name: featured
#    label: Featured on Homepage
#    form_template: form/checkbox.html
